---
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: true
  #require_ansible_repo: false
  require_ansible_source: true
  ansible_source_rev: devel
  require_pip: true
  roles_path: roles
  recursive_additional_copy_path:
    - vars.yml
  extra_vars:
    env_name: test-kitchen
    keepalived: false
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: vagrant-centos7
    driver:
      name: vagrant
      box: minimal/centos7
      provision: true
      customize:
        memory: 512
        usb: "off"
      network:
        - ["private_network", {ip: "192.168.122.253"}]
      vagrantfiles:
        - .vagrant.rb

suites:
  - name: default

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'
